name: Publish

on:
  release:
    types: [released]

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }} # OAuth app client id

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: npm install and build VSIX
        run: |
          npm install
          npm install -g vsce
          vsce package

      - name: Prepublish
        run: npm run vscode:prepublish

      - name: Save logs in case of error
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: logs
          path: /Users/runner/work/.npm/_logs/*.log

      - name: Publish
        if: success()
        run: vsce publish -p ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: vscode-crowdin-*.vsix
